package com.ems.actions;

import java.util.List;

import com.ems.exception.DataAccessException;
import com.ems.model.EventRevenueReport;
import com.ems.model.OrganizerEventSummary;
import com.ems.service.OrganizerService;
import com.ems.util.AdminMenuHelper;
import com.ems.util.ApplicationUtil;

/**
 * Action class for organizer report and analytics operations.
 * Delegates business logic to appropriate services.
 */
public class OrganizerReportAction {
	 private final OrganizerService organizerService;

	 public OrganizerReportAction() {
		 this.organizerService = ApplicationUtil.organizerService();
	 }
	 
	 /**
	 * Gets the total revenue generated by an organizer across all events.
	 * 
	 * @param organizerId the ID of the organizer
	 * @return the total revenue amount
	 */
	 
	 public void getRevenueSummary(int organizerId) {
	        try {
	            List<EventRevenueReport> reports =
	                    organizerService.getRevenueReport(organizerId);

	            if (reports.isEmpty()) {
	                System.out.println("No revenue generated yet.");
	                return;
	            }

	            AdminMenuHelper.printEventRevenueReport(reports);

	        } catch (DataAccessException e) {
	            System.out.println("Error getting revenue summary: " + e.getMessage());
	        }
	    }

	 public void getEventSummary(int organizerId) {
	        try {
	            List<OrganizerEventSummary> summary =
	                    organizerService.getOrganizerEventSummary(organizerId);

	            if (summary.isEmpty()) {
	                System.out.println("No events conducted by this organizer.");
	                return;
	            }
	            
	            AdminMenuHelper.printOrganizerEventSummary(summary);

	        } catch (DataAccessException e) {
	            System.out.println("Error getting event summary: " + e.getMessage());
	        }
	    }
}
